### ISSUE TITLE
Only on/off switch appearing for Rest+

### ISSUE THREAD

**Issue by epheterson** [dgreif/homebridge-hatch-baby-rest#105]
My Rest+ added fine but in Home App I only see a single on/off switch, no brightness/color, audio selector, etc...

The only logs I see are:
```
[3/28/2023, 9:52:04 PM] [HatchBabyRest] Unsupported Product Found: grow
[3/28/2023, 9:52:04 PM] [HatchBabyRest] Configuring 0 Rest+, 0 Rest Mini, 0 Rest 2nd Gen, 1 Rest+ 2nd Gen, and 0 Restore
```

**Comment by dgreif** [comment]
That's correct. The data for the Rest+ is fairly complicated, and relies mainly on "scenes" to set values. The on/off switch will simply turn on your first scene, or turn the whole light off.

**Comment by epheterson** [comment]
You might want to update the readme, it clearly says these features should work except on Rest Mini:

> This homebridge plugin allows you to add the Hatch Rest, Rest+ and Rest Mini, and Restore to HomeKit. For each device, you are able to control the following:
> 
> On / Off - Master switch for both light and sound **
> Brightness and Color **
> Audio Track - represented as a Fan, with different speed levels mapping to different audio tracks. For example, 0% is the "None" track, and 100% is the "Rock-a-Bye" track
> Volume - not available in the Home app, but in some 3rd party HomeKit apps
> Battery level and firmware version (Rest+ only)
> ** Rest Mini does not have a light, so only audio controls are available

The app is able to directly control brightness/color outside of scenes, would be cool to track exposing the extra functionality someday as well.
