### ISSUE TITLE
I have had this pop up in and out again, I think the issue is if there is ANY interruption to the AWS back end a new token is issued.

### ISSUE THREAD

**Issue by simplytoast1** [dgreif/homebridge-hatch-baby-rest#114]
Created a new issue as GH would not let me reopen the old one.   I have had this pop up in and out again, I think the issue is if there is ANY interruption to the AWS back end a new token is issued.

Perhaps we can move the refresh to hourly (or at least give the user to change the default).  I think that would put this issue to bed (pun intended).

_Originally posted by @simplytoast1 in https://github.com/dgreif/homebridge-hatch-baby-rest/issues/59#issuecomment-1877436803_

**Comment by dgreif** [comment]
I reopened the other issue. Not sure when I will get a chance to look at it, but there is better context in that thread so I'll let conversation take place there.
