### ISSUE TITLE
4.3.1 removes Hatch Rest+ Gen 1 and 2 devices

### ISSUE THREAD

**Issue by khiscott** [dgreif/homebridge-hatch-baby-rest#123]
Upgrading to 4.3.1 seems to remove Hatch Rest+ Gen 1 and 2 devices, with “ No supported devices found” in homebridge log and removing the accessories from Home. Downgrading to 4.3 seems to discover them again, however they show as no response in Home.

**Comment by dgreif** [comment]
@khiscott sorry for the bug! Would you mind posting the logs you are seeing? Specifically curious what model name you are seeing

**Comment by khiscott** [comment]
After first downgrade to 4.3
![image](https://github.com/dgreif/homebridge-hatch-baby-rest/assets/49864/007ead2a-36d0-4e92-8ded-b3bec7688e1d)
After re upgrading to 4.1.3 to confirm repro
![image](https://github.com/dgreif/homebridge-hatch-baby-rest/assets/49864/d7acb378-dada-4327-87e2-6f669c9afe21)

**Comment by dgreif** [comment]
Thanks for the logs. Can you give 4.3.2 a try? Added back some of the original logic from 4.3.0 and combined it with 4.3.1. Also marked `grow` as a known but unsupported device so it shouldn't show up in your logs anymore 😄

**Comment by khiscott** [comment]
4.3.2 does remove _grow_ from the logs and the two Rests are discovered again, thanks! Any tips to get them to respond in Home again? Do I need to remove and re-add the hb-rest hub or remove the cached accessories in homebridge settings? Not sure the accessories can be relinked to keep them in the Scenes and Automations...

**Comment by dgreif** [comment]
Unfortunately the automations and settings all got wiped out in this case. I'm really sorry for the bug! As long as your lights are showing up in HomeKit now, you should be good to recreate all of that stuff
