### ISSUE TITLE
4.3.2 Breaks Rest2 support

### ISSUE THREAD

**Issue by raywagner88** [dgreif/homebridge-hatch-baby-rest#125]
Version 4.3.0 allows the first scene to be turned on and off. 4.3.2 breaks this. 
![Homebridge F6B4](https://github.com/dgreif/homebridge-hatch-baby-rest/assets/34992490/ccef69fc-7739-4c88-b857-4b4757698f0a)

**Comment by dgreif** [comment]
@raywagner88 are you able to reliably have this work if you downgrade to 4.3.0? I'm not sure anything meaningful changed with controlling devices between these versions, and the error you shared looks a lot more like a network error than a bug in the latest version. I'd try downgrading and see if the same thing happens, then upgrading again.

**Comment by vdiaz311** [comment]
> @raywagner88 are you able to reliably have this work if you downgrade to 4.3.0? I'm not sure anything meaningful changed with controlling devices between these versions, and the error you shared looks a lot more like a network error than a bug in the latest version. I'd try downgrading and see if the same thing happens, then upgrading again.

Having the same issue many are having. I downgraded to 4.3.0 (works great still) and then updated back, and the problem persists. Going to stay on 4.3.0 for now

**Comment by dgreif** [comment]
Sorry for the headache everyone! I'm working on a fix, but haven't had a chance to finish it out. For now, I'd recommend staying on 4.3.0

**Comment by dgreif** [comment]
Sorry for the long delay! This _should_ be fixed in `4.3.3`. Give it a try and let me know if you still run into issues!
