### ISSUE TITLE
Hatch Baby Rest not triggering

### ISSUE THREAD

**Issue by DCToffee** [dgreif/homebridge-hatch-baby-rest#133]
Hi! I had the plugin and Hatch Rest setup previously and it was working fine, and then it became spotty and then stopped working entirely. I reinstalled everything, and it's showing inside my Home app on my iPhone but when I turn the light on/off nothing happens.

I checked the log in Homebridge and it appears to be getting the instructions properly but just not doing anything with them?

[6/29/2024, 7:06:31 PM] [homebridge-hatch-baby-rest] Turning on first routine for Jude’s Room
[6/29/2024, 7:06:57 PM] [homebridge-hatch-baby-rest] Turning off Jude’s Room
[6/29/2024, 7:07:09 PM] [homebridge-hatch-baby-rest] Turning on first routine for Jude’s Room

Any help gratefully received! Thanks!

**Comment by Nate872711** [comment]
I am also having this issue.  Reinstalled the plugin.  It shows everything connected, but when turning the sound machines on nothing happens.

**Comment by brentleeper** [comment]
Same issue. Only happens with Rest 2nd generation. Restore, Mini, and Rest+ all work without issue.

**Comment by brentleeper** [comment]
Played with this for a while. I don't think it is related to the exact model after all. For some reason, hoobs was attempting to use Ciao for the newly added accessory even though the bridge is configured for Bonjour. Toggling to Ciao, saving, toggling back to Bonjour, and saving again seems to have resolved the issue for me.

**Comment by dgreif** [comment]
Thanks for the update @brentleeper! Which version of the plugin are y'all using?

**Comment by dgreif** [comment]
Closing due to lack of response. Sounds like it was a homebridge issue, not a plugin issue 🤞
