### ISSUE TITLE
Cannot add the platforms entry in HOOBs

### ISSUE THREAD

**Issue by SpaceCadetUWG** [dgreif/homebridge-hatch-baby-rest#21]
I love the idea of being able to control my rest+ on Homekit but I have deployed HOOBs and everytime I try and go into the advanced configuration in HOOBs and add the platforms entry is fails epically. I get the error 

"Unable to save.
Please fix the following errors.

Invalid JSON."

Can you provide some guidance on where I should be adding this in Hoobs or what I have missed here?

**Comment by dgreif** [comment]
You most likely didn't enter the json config properly.  You should be adding something like this to the `platforms` section:

```
  {
     "platform": "HatchBabyRest",
     "email": "someone@gmail.com",
     "password": "secret password"
   }
```

If you already have other plugins under `platforms`, make sure you add a comma before the closing bracket of the previous plugin, like this:

```
   {
     "platform": "Ring"
   }, <<----- don't forget this comma
   {
     "platform": "HatchBabyRest",
     "email": "someone@gmail.com",
     "password": "secret password"
   }
```

**Comment by dgreif** [comment]
any luck @SpaceCadetUWG?

**Comment by SpaceCadetUWG** [comment]
You were totally right it was the missing comma in the logic. Thank you for helping!
