### ISSUE TITLE
Plug in not working

### ISSUE THREAD

**Issue by Bmkenny** [dgreif/homebridge-hatch-baby-rest#26]
Hi,

I installed the plug in for my hatch baby rest, and it successfully loaded into my apple home app, but it doesn't actually turn the nightlight on. This is for my bluetooth night light, and I also have a wifi rest+ and when I try to paste the code in terminal I receive the below error. Can someone please give me some guidance? Thanks!

bash: platforms:: command not found
bash: platform:: command not found
bash: email:: command not found
bash: password:: command not found
bash: ]: command not found

**Comment by Bmkenny** [comment]
Got it, thanks! So I tried copy and pasting the code that you specify in your instructions in the platforms section, and even made sure to separate it from the above plug in with a "," and I keep getting a json code error "invalid json." I'm not sure where to go from here with the wifi rest+. In regards to the bluetooth rest I tried to turn it on and off again and the logs for these actions are below: (they only show the action of trying to turn it on and off - nothing else)

8/23/2020, 9:39:58 PM [Bradlee's Room] Turning on
8/23/2020, 9:40:10 PM [Bradlee's Room] Turning off

Can you advise on any other thoughts that you might have so I can resolve both issues with the plug in not working?

Thanks in advance!

**Comment by Bmkenny** [comment]
Hi, just checking back in to see if you have any suggestions or ideas as to how I can get both of these rest machines to work. Thanks.

**Comment by dgreif** [comment]
@Bmkenny I'm sorry for the long delay! I hope you got past your issues, but if not, here are a few things to try:

For the Bluetooth Rest, you may need to run `sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)`.  This gives NodeJS the ability to use bluetooth without elevated permissions.  Once you run that, restart your homebridge server and see if you are able to control that light.

For the config issue, check out https://github.com/homebridge/homebridge/wiki/Homebridge-Config-JSON-Explained which explains how it work/looks.  You can paste your whole config file contents into https://codebeautify.org/jsonvalidator which should help you narrow down which lines have issues.  If that doesn't help, you can paste it in a new comment, but make sure you remove any usernames, passwords, etc.

**Comment by Bmkenny** [comment]
@dgreif thanks for the reply. I just tried running that command and got the below error message. Not sure what I'm doing wrong. Also, not sure why the line breaks at "readlink" and starts again at the beginning of the same line instead of going to the below line. Also, I was able to get an acceptable config.json in the config file, but the wifi rest + is still not showing up in my accessories. Any other ideas or thoughts as to what I'm doing wrong here? Thanks again!

` -f which node)me/hoobs/.hoobs/etc $ sudo setcap cap_net_raw+eip $(eval readlink 
Failed to set capabilities on file `/home/hoobs/.hoobs/etc/which' (No such file or directory)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file`

**Comment by dgreif** [comment]
Sorry, formatting got weird on that and I didn't notice:

```
sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)
```

For the rest+, is there anything in your logs?  It should say something like `[HatchBabyRest] Configuring 1 Hatch Baby Rest+ light`

**Comment by Bmkenny** [comment]
no problem. Thanks for the correction. I ran that command and nothing seemed to happen, but now it seems that the bluetooth light is operational in the home app. 

The logs show three things that I can see:

9/12/2020, 8:21:41 AM [***** Room] Waiting for bluetooth to power on

9/12/2020, 8:21:41 AM Load homebridge-hatch-baby-rest.HatchBabyRest
9/12/2020, 8:21:41 AM [homebridge-hatch-baby-rest.HatchBabyRest] No configuration found for platform HatchBabyRest

9/12/2020, 8:23:34 AM Load homebridge-hatch-baby-rest.HatchBabyRest
9/12/2020, 8:23:34 AM [homebridge-hatch-baby-rest.HatchBabyRest] No configuration found for platform HatchBabyRest

9/12/2020, 8:48:22 AM [***** Room] Turned off
9/12/2020, 8:48:27 AM [***** Room] Disconnected from ***** Room

Thoughts?

**Comment by dgreif** [comment]
The line that says `Turned off` is promising.  I think it only logs that if it got connected to the light.  I'd try turning it on/off a couple more times and watch the logs.

The `No configuration found for platform HatchBabyRest` log indicates that your config isn't correct still.  Would you mind posting your config and I can point out what needs to be fixed?

**Comment by Bmkenny** [comment]
Yup, for the bluetooth light all seems to be working now. 

For the rest + however, I figured out the issue, but now my Ring accessory doesn't function. I copied and pasted the validated config.json from the code beauty site you provided and it gave me the first section below, but when I paste that into the config.json file in hoobs and save changes it gives me the second pasted section below. Please advise. Thanks!

{
      "platform": "HatchBabyRest",
      "email": "****",
      "password": "****",
        
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "refreshToken": "****,
            "hideCameraSirenSwitch": **,
            "hideInHomeDoorbellSwitch": **,
            "hideAlarmSirenSwitch": **,
            "hideUnsupportedServices": **
        }
    ]
}

`},
        {
            "platform": "Ring",
            "email": "****",
            "password": "****",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "refreshToken": "****",
            "hideCameraSirenSwitch": **,
            "hideInHomeDoorbellSwitch": **,
            "hideAlarmSirenSwitch": **,
            "hideUnsupportedServices": **
        }
    ]
}`

**Comment by Bmkenny** [comment]
It's also worth noting that when I replace the platform name in the second section with "HatchBabyRest" the rest + shows up in the home app and operates correctly, but the Ring accessory stops functioning.

**Comment by dgreif** [comment]
I think you are trying to put both platforms in a single platform config object.  It should look more like this:

```json
"platforms": [
    {
      "platform": "HatchBabyRest",
      "email": "",
      "password": ""
    },
    {
      "platform": "Ring",
      "plugin_map": {
        "plugin_name": "homebridge-ring"
      },
      "refreshToken": "****",
      "hideCameraSirenSwitch": "**",
      "hideInHomeDoorbellSwitch": "**",
      "hideAlarmSirenSwitch": "**",
      "hideUnsupportedServices": "**"
    }
  ]
```

**Comment by dgreif** [comment]
@Bmkenny did that help you get it straightened out?

**Comment by Bmkenny** [comment]
Yes, it seems to have resolved the issues. Although, it's curious since the
first time I tried doing the exact same thing I received errors for json
syntax being incorrect. Neither here nor there now though. Thanks for the
help.

**Comment by mikemcbride** [comment]
Just came here having the same problem (I have 3 of the bluetooth Hatch devices) and this was super helpful! For me, the missing stuff was those bluetooth packages and granting Node access to it. Thanks a bunch for this, it's really useful
