### ISSUE TITLE
Incorrect Status for Multiple Rest+

### ISSUE THREAD

**Issue by schmittx** [dgreif/homebridge-hatch-baby-rest#28]
1) Both Rest+ lights off
2) Using HomeKit, turn on Light A
3) Light A turns on and shows correct status in HomeKit
4) Light B does not physically change but HomeKit now shows same status as Light A

Initially glance seems that "setTargetState" works fine but there's some bug with "getCurrentState" or "getTargetState" and multiple Rest+ devices.

I'm guessing that there's not many of us with multiple Rest+ so I'll be happy to test for you if needed.

**Comment by dgreif** [comment]
@schmittx I actually happen to have two Rest+ so I can take a look at this.  I haven't noticed the behavior that you described, but I also have the lights heavily automated and I don't often look at their state in the Home app.  I've been pretty swamped with the Ring plugin lately, but I'll take a look at this when I get some free time.

**Comment by schmittx** [comment]
@dgreif sounds good!

**Comment by dgreif** [comment]
@schmittx give it a try in the latest version. There was definitely a bug but it was a clear and easy fix.
