### ISSUE TITLE
failed install

### ISSUE THREAD

**Issue by michaeltorbert** [dgreif/homebridge-hatch-baby-rest#29]
I tried both through the config UI X and just doing it in the command line but get the same result. Is there some sort of dependency that's failing? Let me know if there's anything I can do on my end, or if you need any of the actual log.

<img width="800" alt="Screen Shot 2020-10-20 at 4 15 06 PM" src="https://user-images.githubusercontent.com/17364998/96639972-7dfb3c00-12f0-11eb-8cbb-61c97ead813a.png">
<img width="805" alt="Screen Shot 2020-10-20 at 4 15 36 PM" src="https://user-images.githubusercontent.com/17364998/96639979-7fc4ff80-12f0-11eb-821c-b398aa2b7005.png">

**Comment by dgreif** [comment]
@michaeltorbert it's failing to build the bluetooth dependencies needed for the original Hatch Rest nightlight.  Are you using a Rest or Rest+ (wifi) night light?  Could you also provide the following:

Operating System:
Node Version:
Npm Version:

**Comment by michaeltorbert** [comment]
@dgreif I'm using this https://smile.amazon.com/gp/product/B06XMRCC94

Operating System: MacOS 10.15.4 
Node Version: 14.13.0
Npm Version: 6.14.8

**Comment by dgreif** [comment]
@michaeltorbert see https://medium.com/flawless-app-stories/gyp-no-xcode-or-clt-version-detected-macos-catalina-anansewaa-38b536389e8d

**Comment by ddorato** [comment]
@dgreif Should I follow the same guide for the Rest+ (WiFi)

**Comment by dgreif** [comment]
@ddorato if you are seeing the same error (`gyp: No XCode or CLT version detected!`), then yes.  Based on previous interactions, I assumed you already had the plugin up and running

**Comment by ddorato** [comment]
#1 Fantastic memory... #2 New Machine.. SMH... Stupid simple solution, thx!

**Comment by kriskoeller** [comment]
I'm also having a failed install on a Raspberry Pi as per the screen shot. Updated NodeJS and NPM. Attempting to connect to a Hatch Baby Rest +. 
<img width="1276" alt="Screen Shot 2020-10-26 at 5 54 59 PM" src="https://user-images.githubusercontent.com/16693530/97232930-75a17600-17b4-11eb-9fd2-6eb93cea4332.png">

**Comment by michaeltorbert** [comment]
So does this mean I need xcode installed on the Mac Mini for it to run this plugin?

**Comment by dgreif** [comment]
Closing since @michaeltorbert got his figured out.  @kriskoeller feel free to open a new issue if you are still having problems
