### ISSUE TITLE
"Waiting for bluetooth to power on"

### ISSUE THREAD

**Issue by ckeone** [dgreif/homebridge-hatch-baby-rest#3]
Any suggestions as to how to fix the "Waiting for bluetooth to power on" I'm seeing when starting HomeBridge.  I see:

[Homebridge] [12/12/2019, 15:29:50] [Bedtime] Initializing HatchBabyRest accessory...
[Homebridge] [12/12/2019, 15:29:50] [Bedtime] Waiting for bluetooth to power on

 I'm running on supported hardware, config is done correctly and Bluetooth is running on my Pi, but I cannot seem to get this to connect.

(As an aside, thank you for this!).  Been waiting for almost a year for somebody smarter than me to get this up and running.

**Comment by dgreif** [comment]
@ckeone I'm glad to see some interest in this plugin!  This is most likely a permissions issue that you are running into.  Check out https://github.com/dgreif/homebridge-hatch-baby-rest/issues/2#issuecomment-565296016 and let me know if that helps you progress

**Comment by ckeone** [comment]
That was the first thing I tried, but sadly no luck.  I'm using HOOBS and it's seemingly having issues with all BLE accessories (can't find bluetooth-hci-socket) so I'll try on a fresh install tomorrow as there's some weird stuff going on with all BLE stuff.

**Comment by dgreif** [comment]
Sounds good.  If you do find a set of commands that you need to run, could you please post them?  I would like to add some documentation to the Readme, but I don't have a clean rpi laying around

**Comment by dgreif** [comment]
@ckeone can you try running the following command and then give it a try?

`sudo apt-get install bluetooth bluez libbluetooth-dev libudev-dev` (pulled from https://www.npmjs.com/package/@abandonware/noble#ubuntudebianraspbian)
