### ISSUE TITLE
Stops at scanning for device...Bluetooth permissions

### ISSUE THREAD

**Issue by wholesomezine** [dgreif/homebridge-hatch-baby-rest#34]
Stops at scanning for device... pretty sure it’s a permissions issue like others have had but previous solutions aren’t helping I am running on a Mac mini...

**Comment by dgreif** [comment]
@wholesomezine try installing xcode if you don't have it installed already.  Here are the requirements for macos:

* OS X 10.7 or greater
 * with a BLE adapter built in or a compatible USB Bluetooth 4.0 adapter
* Xcode

**Comment by wholesomezine** [comment]
Turns out It’s just a range issue moving the rest closer made it work. Unfortunately my wife wants it to stay where it is and I can’t  move the Mac. Thanks so much for replying!

**Comment by dgreif** [comment]
Ahh, makes sense.  I had that issue with mine as well.  Ended up getting the Rest+, which is wifi and way more reliable.  Good luck!
