### ISSUE TITLE
Better as a RGB light?

### ISSUE THREAD

**Issue by arvathrowaway** [dgreif/homebridge-hatch-baby-rest#40]
Completely ignorant is how to actually code it, but couldn't this device just act like a always-on LED strip (or at least the BR Rest, which we have one of). The power on could set it to a certain state, you could push hue variables, brightness variables, and the sound on and off could simply be controlled by a separate switch or "light" for on/off and volume?

**Comment by dgreif** [comment]
@arvathrowaway completely valid idea.  The Rest+ is set up as an RGB light, but I didn't have all the color conversion code in place when I did the original Rest.  I think it should be relatively easy to add this functionality.  Not sure when I'll be able to get to it, but I'll keep it on my TODO list.

**Comment by dgreif** [comment]
This is done in v3 of the plugin.  See https://github.com/dgreif/homebridge-hatch-baby-rest/wiki/Upgrading-from-v2-to-v3 for details about the changes

**Comment by arvathrowaway** [comment]
This is awesome. Thanks!

**Comment by dgreif** [comment]
Glad to hear it, let me know how the update works for you

**Comment by arvathrowaway** [comment]
Just tested it out. My setup is two lights, old BT hatches. Both transition over perfectly config-wise and both are working flawlessly!
