### ISSUE TITLE
Set accessory info serial number to MAC address

### ISSUE THREAD

**Issue by schmittx** [dgreif/homebridge-hatch-baby-rest#42]
As a stop gap until a Python version can be made, I want to use Homebridge --> HomeAssistant (via HomeKit Controller component). But, HomeAssistant cannot handle accessories without a serial number/unique identifier specified (currently set to `Unknown`). See this [issue](https://github.com/chrisjshull/homebridge-nest/issues/301) for same concern with another Homebridge plugin.

Can the MAC address (or some other stable identifier) be used for the serial number?

**Comment by dgreif** [comment]
Great idea @schmittx.  Mac address is now used as the serial number in `2.2.1`
