### ISSUE TITLE
Rest (BTLE) stops responding to commands

### ISSUE THREAD

**Issue by idsnowghost** [dgreif/homebridge-hatch-baby-rest#43]
Just upgraded to v3 yesterday. I have a Hatch Rest that I had successfully working on v2.

I've set up a Scene to: set the color, track and switch to "on". It will work one time after starting up homebridge then won't connect again.

Seems like it's trying to connect to the device multiple times initially, then just ignores all commands after that:

Feb 09 08:17:00 homebridge homebridge[1656]: [2/9/2021, 8:17:00 AM] [HatchBabyRest] Turning on James Night Light
Feb 09 08:17:00 homebridge homebridge[1656]: [2/9/2021, 8:17:00 AM] [HatchBabyRest] Connecting to Hatch Rest...
Feb 09 08:17:00 homebridge homebridge[1656]: [2/9/2021, 8:17:00 AM] [HatchBabyRest] Connecting to Hatch Rest...
Feb 09 08:17:00 homebridge homebridge[1656]: [2/9/2021, 8:17:00 AM] [HatchBabyRest] Connected to Hatch Rest
Feb 09 08:17:00 homebridge homebridge[1656]: [2/9/2021, 8:17:00 AM] [HatchBabyRest] Connected to Hatch Rest
Feb 09 08:17:06 homebridge homebridge[1656]: [2/9/2021, 8:17:06 AM] [HatchBabyRest] Disconnected from Hatch Rest
Feb 09 08:17:24 homebridge homebridge[1656]: [2/9/2021, 8:17:24 AM] [HatchBabyRest] Turning off James Night Light
Feb 09 08:17:24 homebridge homebridge[1656]: [2/9/2021, 8:17:24 AM] [HatchBabyRest] Connecting to Hatch Rest...
Feb 09 08:19:51 homebridge homebridge[1656]: [2/9/2021, 8:19:51 AM] [HatchBabyRest] Turning on James Night Light
Feb 09 08:19:51 homebridge homebridge[1656]: [2/9/2021, 8:19:51 AM] [HatchBabyRest] Connecting to Hatch Rest...
Feb 09 08:20:26 homebridge homebridge[1656]: [2/9/2021, 8:20:26 AM] [HatchBabyRest] Turning off James Night Light
Feb 09 08:20:26 homebridge homebridge[1656]: [2/9/2021, 8:20:26 AM] [HatchBabyRest] Connecting to Hatch Rest...
Feb 09 08:20:43 homebridge homebridge[1656]: [2/9/2021, 8:20:43 AM] [HatchBabyRest] Turning on James Night Light
Feb 09 08:20:43 homebridge homebridge[1656]: [2/9/2021, 8:20:43 AM] [HatchBabyRest] Connecting to Hatch Rest...

**Comment by dgreif** [comment]
That's really interesting, definitely could be a bug in the connection logic.  The double "Connecting" shouldn't happen on the first try, it should only show one connecting.  I'll take a look at it when I get some time.  For now, if you generally keep a consistent color/sound, you can set up your automation to only use the on/off switch and the light should remember its previous color/sound settings

**Comment by idsnowghost** [comment]
Ditched the Scene for now.. still having issues.

It seems the "On/Off" switch won't actually toggle the Rest off. After toggling to the off position, you can manipulate the light brightness slider and it will adjust brightness and finally quickly turn the Rest off.

**Comment by dgreif** [comment]
Can you post the logs from that scenario?

**Comment by idsnowghost** [comment]
Turning on (works fine):
Feb 09 09:16:00 homebridge homebridge[2676]: [2/9/2021, 9:16:00 AM] [HatchBabyRest] Turning on James Night Light
Feb 09 09:16:00 homebridge homebridge[2676]: [2/9/2021, 9:16:00 AM] [HatchBabyRest] Connecting to Hatch Rest...
Feb 09 09:16:01 homebridge homebridge[2676]: [2/9/2021, 9:16:01 AM] [HatchBabyRest] Connected to Hatch Rest
Feb 09 09:16:07 homebridge homebridge[2676]: [2/9/2021, 9:16:07 AM] [HatchBabyRest] Disconnected from Hatch Rest

Turning off (no change on Rest device):
Feb 09 09:16:52 homebridge homebridge[2676]: [2/9/2021, 9:16:52 AM] [HatchBabyRest] Turning off James Night Light
Feb 09 09:16:52 homebridge homebridge[2676]: [2/9/2021, 9:16:52 AM] [HatchBabyRest] Connecting to Hatch Rest...
Feb 09 09:16:52 homebridge homebridge[2676]: [2/9/2021, 9:16:52 AM] [HatchBabyRest] Connected to Hatch Rest
Feb 09 09:16:57 homebridge homebridge[2676]: [2/9/2021, 9:16:57 AM] [HatchBabyRest] Disconnected from Hatch Rest

Adjusting brightness (quickly does then 'notices' the switch is off and turns Rest off):
Feb 09 09:17:38 homebridge homebridge[2676]: [2/9/2021, 9:17:38 AM] [HatchBabyRest] Connecting to Hatch Rest...
Feb 09 09:17:38 homebridge homebridge[2676]: [2/9/2021, 9:17:38 AM] [HatchBabyRest] Connected to Hatch Rest
Feb 09 09:17:45 homebridge homebridge[2676]: [2/9/2021, 9:17:45 AM] [HatchBabyRest] Disconnected from Hatch Rest

**Comment by mikelinden1** [comment]
I have the same issue. It actually caused my hatch to freeze completely and the hatch all couldn't even connect. It looks like it's trying to connect multiple times and the hatch can't take all of the connection requests.

**Comment by dgreif** [comment]
Yeah, once it fails to connect a single time, future attempts will fail. It's something I need to look into but haven't had the time. Sorry for the frustration!

**Comment by downquark** [comment]
We're here because we were seeing the same issue with the hatch official app and now with this plugin:
> It seems the "On/Off" switch won't actually toggle the Rest off.

Same "work-around" works for us too. What we'd really like is the okay to wake program to again, so that's what we'll be looking into.

**Comment by jleesnow** [comment]
@dgreif Any update on this? I'm seeing the same issue on first install of this plugin

**Comment by dgreif** [comment]
No updates yet, sorry.  Free time has been pretty limited

**Comment by Pelagious** [comment]
I can confirm the same issue as above. It mainly seems to occur when I try to use a scene that controls the switch, the light and the fan at the same time.

The best work around I have found has been to just use scenes that adjust the switch only. Light and fan settings are remembered. As long as you don't need to play with brightness and audio track you should be fine.

**Comment by shadowa4** [comment]
Hi,

Not sure if this is related to the standing bug, but I am seeing similar behavior. I have homebridge running on a RPI4 controlling a number of devices, but of course, also a hatch rest product, specifically the original bluetooth hatch rest.

Earlier this week I updated the plugin, the homebridge instance, and raspian as a whole. After these updates I can no longer control the device from homekit as I used to before. I have observed the following behaviors:

- Homebridge and the plugin still find and "seem to" issue commands to the hatch, however, the actions do not take place (lights dont change, on/off does not respond, etc).

- No error messages appear on homekit (such as not responing), and the on/off, track and light tiles remain as they always have been.
-
- When ssh'd into the RPI4 and into the bluetooth service, I can see that when I press the homekit tiles for an action, the RPI4 connects/disconnects to the hatch, but no command is issued and no actions takes place.

I have tried the usual trusting/pairing suggestions online, and even the two commands you posted on the main page for this plugin to no improvement. Unsure at this point if this is a plugin or a RPI4 BT issue. I did try to revert to even version 2.x.x of the plugin, and nothing changed; even when uninstalling and starting from scratch.

**Comment by dgreif** [comment]
@shadowa4 my guess is the raspian update modified some of the bluetooth permissions/settings on your rpi.  The plugin uses the `noble` npm module to interact with bluetooth, and there are [detailed installation instructions](https://www.npmjs.com/package/@abandonware/noble#installation) for getting it working on each platform.  If none of those steps fix the issue for you, I don't have any good suggestions on how to fix it.  Bluetooth is a really tricky thing to interact with, and there are a ton of system-level issues that can prevent it from working.  Personally I have moved to all wifi hatch lights because they are far more reliable than the bluetooth + rpi setup.

**Comment by shadowa4** [comment]
@dgreif Thanks for the info. I've followed those guides to no avail. So, I'm looking for a Wi-Fi hatch as we speak. I assume that one just gets discovered with your email/password fields?

**Comment by olchickenbeard** [comment]
I'm having the same issue as @shadowa4, but with wifi models. I have two, all four tiles for each one show up in Homebridge, they appear to be toggling and working in Homebridge with no error logs, but they aren't actually responding to anything.

**Comment by dgreif** [comment]
I'm really not doing much maintenance on the bluetooth side of this plugin any longer. For the best experience, I recommend buying one of the newer wifi lights from Hatch. The bluetooth is just too complicated given the hardware requirements, and the fact that bluetooth warries widely between different devices (rpi vs mac vs ...). PRs welcome if anyone finds improvements.
