### ISSUE TITLE
HomeKit state when light color set to "None"

### ISSUE THREAD

**Issue by schmittx** [dgreif/homebridge-hatch-baby-rest#45]
Regarding the Lightbulb service representing the light function on a Hatch Rest+:

If I set the color to "none" within the Hatch app, the HomeKit status is displayed as white (RGB = 255, 255, 255) color and retains previous brightness value even though the light on the physical Rest+ is turned off.

Can this be fixed to show the lightbulb as "off" when the "none" color option is selected within the Hatch app?

**Comment by dgreif** [comment]
Thanks for reporting, I'll try to take a look at this in the next few days

**Comment by mkinsella** [comment]
Thank you @dgreif! This would be the cherry-on-top of the latest v3 release as it's the only thing that is stopping me from fully using the Homebridge/HomeKit integration.
