### ISSUE TITLE
Integration into Home Assistant

### ISSUE THREAD

**Issue by MattW2** [dgreif/homebridge-hatch-baby-rest#46]
Hi, just wondering if you had looked into integrating this into Home Assistant? I'm most interested in integrating your Rest bluetooth library and integrating it into ESPHome such that an ESP32 could be used as the interface between the Rest and Home Assistant.

I first found about your project on the Home Assistant Forum, [Hatch Baby Rest+, Home Assistant Forum](https://community.home-assistant.io/t/hatch-baby-rest/188651)

**Comment by dgreif** [comment]
@MattW2 sorry for the extremely delayed response.  In the forum you linked, it sounds like someone was able to get it working by exposed the hatch plugin as a child bridge and adding that to HA.  It's not an area that I aim to explicitly support, so this isn't something I plan to work on.  Happy to accept PRs if there is something that needs to be changed to make it work better.
