### ISSUE TITLE
UnhandledPromiseRejectionWarning on Windows

### ISSUE THREAD

**Issue by jbryan83** [dgreif/homebridge-hatch-baby-rest#5]
I am trying to get this working on Homebridge on a Windows 10 machine. I was able to add the device to Homekit, but when I turn it off an on from within Homekit, nothing actually happens. Looking at the Homebridge logs, I get the following error each time:

UnhandledPromiseRejectionWarning: Error: No compatible USB Bluetooth 4.0 device found!
at BluetoothHciSocket.bindUser
at BluetoothHciSocket.bindRaw
at Hci.init
at NobleBindings.init
at Noble.get
at HatchBabyRest.<anonymous>
at Generator.next
etc...

I have a bluetooth 4.0 compatible adapter in my PC, so I'm not sure what to think of that error message. Any ideas?

**Comment by dgreif** [comment]
Check out the windows setup instructions for the underlying bluetooth library I am using: https://github.com/abandonware/noble#windows

If those instructions don't solve it for you, I'm afraid there isn't much I can do.  Let me know how it turns out!
