### ISSUE TITLE
Simple Switch Control

### ISSUE THREAD

**Issue by nm2124** [dgreif/homebridge-hatch-baby-rest#53]
Hi there,

Thank you for your work on this plugin, I've been finding it very useful. I was just wondering if it would be possible to just expose a simple On/Off switch for each of my Hatch Sound Machines connected. They are already configured, I just want to be able to turn them on and off in HomeKit and to not see any of the other settings.

Thank you!

**Comment by dgreif** [comment]
There is a "master" switch within each of the components.  You can use this switch for automations if you don't want to set all of the other settings every time.  I'd prefer not to add an extra setting to slim down to _just_ that switch as it just makes the code more complicated to maintain, sorry!
