### ISSUE TITLE
Hide Accessory

### ISSUE THREAD

**Issue by simplytoast1** [dgreif/homebridge-hatch-baby-rest#54]
I have two Hatch devices, is it possible to hide one of them?

**Comment by dgreif** [comment]
If they are bluetooth, you can simply remove them from the config.  If they are WiFi, then no.  I haven't added any "hide" options to this plugin and don't really plan to at this point.  You can always stick them in a different room on the HomeKit side and remove them from favorites if you don't want to see one of them.
