### ISSUE TITLE
Replace 3-FAN accessory with 36-TV_STREAMING_STICK

### ISSUE THREAD

**Issue by steveredden** [dgreif/homebridge-hatch-baby-rest#57]
Not sure how it's done in [homebridge-adb](https://github.com/dwaan/homebridge-adb/blob/master/index.js#L101), but it's able to define "inputs" and execute specific commands based them.

![image](https://user-images.githubusercontent.com/35814432/129104288-370710ec-49a7-4375-b4b2-df35b1d6e4db.png)

Can you, for the 11+off sound tracks, implement this kind of device, instead of a fan?

**Comment by dgreif** [comment]
I looked into it some and we would have to convert the sound portion to a `Television` service.  This might give the added benefit of controlling volume and selecting track by name, but it would be a breaking change to the plugin and I'm not sure using a television is any more correct than using a fan.  Given how few audio channels there are, I think the current solution works well.  This is something I might accept a PR for if someone spends the time to dig into all the details of setting up a Television service, but it's not something I want to take on right now myself.  Thanks for pointing it out tho!  Good to know there is at lease some service that has named inputs!
