### ISSUE TITLE
Not responding while Online

### ISSUE THREAD

**Issue by simplytoast1** [dgreif/homebridge-hatch-baby-rest#59]
Since the latest update - my hatch devices (Rest+ & Restore) are ignoring (or not recieving) HB commands.  A simple reboot of the Hb instance restores functionality.

Both devices have a static IP and for some reason in a rollback of a previous version of the plugin seems to maintain stability although 3.2.3 only updated dependancies.

**Comment by dgreif** [comment]
Can you try updating to the latest version again to verify that the latest version in fact caused it to break for you?

**Comment by simplytoast1** [comment]
I ran Homebridge in Debug mode and after about 24 hours of uptime my Hatch+ and Hatch restore no longer respond to HB commands.

I looked at the debug logs but it seems nothing useful is in there.

[8/29/2021, 10:28:05 PM] [homebridge-hatch-baby-rest] Turning off Restore
[8/29/2021, 10:28:07 PM] [homebridge-hatch-baby-rest] Turning on first betime step for Restore

(My testing)


After a reboot of the HB service the Hatch devices are responding to commands.

**Comment by FlipABit** [comment]
I'm having the same issue. The logs seem to indicate the plugin is sending commands and there is no sign of errors, but the hatch doesn't not respond to the commands. Rebooting home bridge restores functionality for some amount of time, but then will stop responding again.

**Comment by goobags** [comment]
I am also having issues. Only new to homebridge and this is my first plug in. It worked initially then stopped responding after a few days. Since seeing the above comments I have restarted homebridge and the Rest+ is responding to commands and receiving manual state changes. I will monitor over the next few days to see if it loses connection again.

**Comment by williamw** [comment]
Same exact issue here. I have a Rest Mini and Rest+. After starting HomeBridge, 12-24 hours later the devices stop responding to commands from this plugin. Nothing in the logs. Simple reboot of HomeBridge resolves the problem for another 12-24 hours.

**Comment by goobags** [comment]
I monitored Homebridge over a day or so and it again lost connection to the Rest+. I have since uninstalled this plugin and rely on the Hatch app

**Comment by dgreif** [comment]
Hey all, sorry for not getting around to this sooner.  I've been noticing this same issue over the past week or two and have been watching my logs closely to see if there are any errors I can go off of.  Ultimately, I think I just need to refresh the connection with AWS every 8 hours or so to keep it fresh, and not count on an auth error to tell me to reconnect.  I don't have time to get it fixed up today but will get something out as soon as I can. Thanks for your patience!

**Comment by dgreif** [comment]
Just released v`3.2.4` which will automatically reconnect every 8 hours.  I'll be keeping a close eye on it over the next few days, but hopefully this resolves the issue!

**Comment by simplytoast1** [comment]
Seems to be working great here @dgreif !   Proud to be a supporter!

**Comment by simplytoast1** [comment]
Hate to open this issue again, but it seems the token issue has been reoccurring for me.  Same behavior.  Simple restart of the plugin fixes it.

**Comment by simplytoast1** [comment]
I have had this pop up in and out again, I think the issue is if there is ANY interruption to the AWS back end a new token is issued.

Perhaps we can move the refresh to hourly (or at least give the user to change the default).  I think that would put this issue to bed (pun intended).

**Comment by simplytoast1** [comment]
Following up on the token refresh interval being adjustable?
