### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by sedonapup** [dgreif/homebridge-hatch-baby-rest#6]
Trying to install on a raspberry pi 3 using the command as provided
![image](https://user-images.githubusercontent.com/37234733/71706854-21f11680-2db5-11ea-9e1e-6fa395ed5e91.jpg)

As well as with root privilege
![image](https://user-images.githubusercontent.com/37234733/71707030-ab084d80-2db5-11ea-9ba0-ebb4f151025b.jpg)

Both attempts seem to have permission issues with /usr/lib/node_modules/. Any suggestions?

**Comment by dgreif** [comment]
This is an npm issue and not something directly related to this plugin.  While I would love to help, this is completely dependent on your computer and the best way to solve it is to just start googling for errors you are seeing there.  I wish you luck!
