### ISSUE TITLE
Controlling Volume of Rest+ when Linked to Home Assistant via Homebridge

### ISSUE THREAD

**Issue by rml1111** [dgreif/homebridge-hatch-baby-rest#63]
I'm using this Homebridge in conjunction with Home Assistant to control my two Hatch Rest+ sound machines. Everything all of the devices and entities import into Home Assistant with the exception of volume control. Are there any plans to update to include volume control that would be compatible with Home Assistant? I have tried homebridge-hatch-baby-rest-volume plugin (a fork from this repository), however, it has not been updated and I am experience an issue only one device being imported and linked to the incorrect devices (explanation of issue here: https://github.com/home-assistant/core/issues/50811). Thank you for creating this very useful plugin.

**Comment by dgreif** [comment]
@rml1111 I hadn't planned to add volume controls since the native Home app doesn't support volume adjustment for speakers.  I'll keep it in mind and update here if I add it down the road.

**Comment by cmrenus** [comment]
Is there any specific reason that the speaker control doesnt port over from homebridge to HA? I dont see why it wouldnt, since it is there in homebridge

**Comment by dgreif** [comment]
I'm not sure @cmrenus, I haven't worked with the HA integration at all. Sorry!
