### ISSUE TITLE
Depricated Call

### ISSUE THREAD

**Issue by simplytoast1** [dgreif/homebridge-hatch-baby-rest#66]
I updated my HomeBridge Node to v16.13.1 and filled the HB Node upgrade guide but it could not recompile the Rest plugin and generates the following error on load.

[1/3/2022, 3:48:24 PM] [homebridge-hatch-baby-rest] Configuring 0 Rest, 1 Rest+, 0 Rest Mini, and 1 Restore Devices
(node:81434) [node-fetch#buffer] DeprecationWarning: Please use 'response.arrayBuffer()' instead of 'response.buffer()'
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by dgreif** [comment]
Do you have any logs to show the error? Maybe try removing and re adding the plugin

**Comment by simplytoast1** [comment]
I reinstalled the plugin and it worked.  What I think happened was there was an issue with the Node upgrade so reinstalling mode and the plugin worked!  Closing the issue.
