### ISSUE TITLE
MaxListenersExceededwarning: Possible EventEmitter memory leak det ected. 11 connect listeners added to [Peripheral].

### ISSUE THREAD

**Issue by shaintoth** [dgreif/homebridge-hatch-baby-rest#67]
After restarting homebridge, the first changes to the Hatch will take effect and connect successfully, but all subsequent requests are met with the titular error message. 

Have attempted resetting the Rest but received the same issue. 
![B7DC910E-8E54-44DF-A56F-C503C992C152](https://user-images.githubusercontent.com/34776408/150594129-777fe974-d034-4fe0-8af3-2af09bad23c7.png)

**Comment by shaintoth** [comment]
![2F6EEC53-2EAC-43C7-A652-4858BBE7670D](https://user-images.githubusercontent.com/34776408/150595331-d6cf4fbf-6f0d-4104-8e4e-3560c89e925f.png)

**Comment by dgreif** [comment]
I'm really not doing much maintenance on the bluetooth side of this plugin any longer. For the best experience, I recommend buying one of the newer wifi lights from Hatch. The bluetooth is just too complicated given the hardware requirements, and the fact that bluetooth warries widely between different devices (rpi vs mac vs ...). PRs welcome if anyone finds improvements.

**Comment by shaintoth** [comment]
Thanks for the response, maybe when I have a little bit of time I’ll try putting in a PR!I do miss Siri control of it!On Aug 28, 2022, at 10:44 AM, Dusty Greif ***@***.***> wrote:﻿
I'm really not doing much maintenance on the bluetooth side of this plugin any longer. For the best experience, I recommend buying one of the newer wifi lights from Hatch. The bluetooth is just too complicated given the hardware requirements, and the fact that bluetooth warries widely between different devices (rpi vs mac vs ...). PRs welcome if anyone finds improvements.
