### ISSUE TITLE
Python API?

### ISSUE THREAD

**Issue by schmittx** [dgreif/homebridge-hatch-baby-rest#7]
Great work on the Homebridge plugin, I'd love to get this into Home Assistant as well. Have you considered making a Python API for the Rest/Rest+? I could help with the Home Assistant integration side of it.

**Comment by dgreif** [comment]
I'm much more comfortable with node than I am with python.  I'm happy to answer questions if you decide to port this to python yourself.  Also check out https://github.com/Marcus-L/m4rcus.HatchBaby.Rest if you want a C# reference (that's where I got a lot of my initial info for the original Rest)

**Comment by schmittx** [comment]
Sounds good, I'll look into it and let you know if I have questions.

**Comment by et** [comment]
@schmittx - did you ever get a chance to make the home assistant version? If not, I’m interested in taking in on but didn’t want to reinvent the wheel if you already have something. Got two months before due date so time is fleeting 😜

**Comment by schmittx** [comment]
@et Unfortunately, no, I never did dive into it. I got sidetracked working on some other Home Assistant custom components. That being said though, I'm still super interested in this and I'll still be glad to help with the Home Assistant integration side of it.

**Comment by zcampau** [comment]
@schmittx @et I'm looking for a home assistant integration for the Hatch Rest as well, if anyone ended up figuring it out.

**Comment by schmittx** [comment]
@zcampau Same here...

**Comment by et** [comment]
Baby came sooner than expected so I never had a chance 😁

**Comment by yoshi43** [comment]
I would love to see this as well!

**Comment by niemyjski** [comment]
Any luck?

**Comment by schmittx** [comment]
@dgreif I've started a Python port of this but am new to AWS IoT world. I believe I need to connect to the AWS MQTT broker using the creds returned from the `cognito-identity` call, correct? Then it becomes a normal MQTT publish/subscribe thing? Any idea if I can connect to AWS MQTT using a GUI app to view the topics/messages for troubleshooting?

**Comment by dgreif** [comment]
@schmittx I don't know of any GUI for AWS MQTT, but I didn't really search for one when I did the initial discovery for this plugin.  Once you are connected with the client, it's pretty easy to log all the events coming at you, and you can look through my code to see any communication going up to the MQTT server

**Comment by JonLaliberte** [comment]
@schmittx Any luck with the Python port of this? I didn’t see a repo for it in your GitHub profile.

**Comment by schmittx** [comment]
@JonLaliberte No, I looked into the AWS MQTT a bit but it was a steep learning curve for me and I didn't have that much time to pursue further.
