### ISSUE TITLE
Failed Plugin Install

### ISSUE THREAD

**Issue by jrod07** [dgreif/homebridge-hatch-baby-rest#70]
I've recently stood up a Synology NAS with Homebridge installed to assist me to explose devices that are not natively supported by HomeKit.

I've successfully installed other plugins, however, when it comes to this plugin (homebridge-hatch-baby-rest), I get the following error message:

*********************************************************************************************************************************************
*********************************************************************************************************************************************
USER: homebridge
DIR: /volume1/@appdata/homebridge
CMD: npm install -g homebridge-hatch-baby-rest@latest

npm ERR! code 1
npm ERR! path /volume1/@appdata/homebridge/lib/node_modules/homebridge-hatch-baby-rest/node_modules/@abandonware/noble
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.3.0
npm ERR! gyp info using node@16.13.2 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.8 found at "/usr/bin/python3.8"
npm ERR! gyp info spawn /usr/bin/python3.8
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/volume1/@appdata/homebridge/lib/node_modules/homebridge-hatch-baby-rest/node_modules/@abandonware/noble/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/var/packages/homebridge/home/.cache/node-gyp/16.13.2/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/var/packages/homebridge/home/.cache/node-gyp/16.13.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/var/packages/homebridge/home/.cache/node-gyp/16.13.2/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/volume1/@appdata/homebridge/lib/node_modules/homebridge-hatch-baby-rest/node_modules/@abandonware/noble',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: not found: make
npm ERR! gyp ERR! stack     at getNotFoundError (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:10:17)
npm ERR! gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:57:18
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at step (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:54:21)
npm ERR! gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:71:22
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at subStep (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:69:33)
npm ERR! gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:80:22
npm ERR! gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! System Linux 4.4.180+
npm ERR! gyp ERR! command "/volume1/@appstore/homebridge/app/bin/node" "/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /volume1/@appdata/homebridge/lib/node_modules/homebridge-hatch-baby-rest/node_modules/@abandonware/noble
npm ERR! gyp ERR! node -v v16.13.2
npm ERR! gyp ERR! node-gyp -v v8.3.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/packages/homebridge/home/.npm/_logs/2022-03-09T16_03_17_609Z-debug.log

Command failed. Please review log for details.
******************************************************************************************************************************************************************************************************************************************************************************************

Has anyone else experienced this?  Apologies if this is a duplicate topic, I wasn't able to find the same issue in other topics.

Thanks!

**Comment by dgreif** [comment]
Please see the install docs at https://www.npmjs.com/package/@abandonware/noble#installation
You can also google "node gyp Synology" and see if there are any recommendations on how to get it to install.  Node gyp is a bit of a pain, and getting it working is unique to each environment so unfortunately it's not something I can fix at the plugin level.
