### ISSUE TITLE
Hide "fan" accessory

### ISSUE THREAD

**Issue by town3r** [dgreif/homebridge-hatch-baby-rest#71]
Would be nice if we could hide specific accessories like the fan.

**Comment by dgreif** [comment]
Hey @town3r, thanks for the suggestion.  I've added similar configuration options in other plugins and have found that it makes maintenance harder, and users continue to request more complex configuration over time.  I'd like to keep this plugin simple, so I don't plan to add this configuration option.

**Comment by town3r** [comment]
What about an input toggle to make the tracks easier to select?

Not sure if that's something that would be possible.

Looks like someone else suggested it [here](https://github.com/dgreif/homebridge-hatch-baby-rest/issues/68)

Might be able to borrow some ideas from this plugin. :)

https://github.com/tavicu/homebridge-samsung-tizen/wiki/Inputs
