### ISSUE TITLE
Issues with Master On/Off Switch

### ISSUE THREAD

**Issue by town3r** [dgreif/homebridge-hatch-baby-rest#73]
Should the Master On/Off Switch successfully turn off the device when toggled to Off if both the Light & Fan accessories were enabled by toggling it on?

Is this a known issue with the Bluetooth only Rest?

![image](https://user-images.githubusercontent.com/12396203/162998548-85721580-e6d7-4b26-a839-1a18bff9b44b.jpeg)

**Comment by dgreif** [comment]
The device should turn off both sound and light in this scenario, though they may still individually show as "on" in the Home app
