### ISSUE TITLE
Any plans to refactor the web API or the bluetooth API out into standalone packages?

### ISSUE THREAD

**Issue by adepssimius** [dgreif/homebridge-hatch-baby-rest#75]
I'd love to use these with home assistant, but I don't use homekit at all. I'd be happy to create repos with just these components and hand the ownership over to you with a PR here to add them as dependencies and use them, I just don't want to redo things that are already in the works.

Also did you happen to notice if there was a local TCP API? I'd start port scanning but my kid is sleeping at the moment and I don't want to risk my wife's wrath :)

**Comment by dgreif** [comment]
Hey @adepssimius, sorry for the delayed response.  I haven't heard a large need to refactor these APIs for use outside homekit, but it's possible.  I do something similar in https://github.com/dgreif/ring.  It is a fair amount of extra setup though, so I'd prefer to avoid it for now.  If I get a few more comments on here asking for it I'll consider it.  For now you are welcome to fork what I have here and build what you need on top of it.
