### ISSUE TITLE
Hide Rest Accessories

### ISSUE THREAD

**Issue by bsteinbach112** [dgreif/homebridge-hatch-baby-rest#77]
Would it be possible to add a configuration setting to hide certain "devices" within HomeKit? At this point I only want to be able to control whether a Rest+ is on or off. Would it be possible to add a setting to hide the volume (fan) and light (color/brightness) tiles?

**Comment by dgreif** [comment]
I'd prefer to keep the configuration for the plugin as simple as possible.  I went the route of adding a lot of "hide" options in `homebridge-ring` and I end up getting requests to add a new hide option for every new feature I add.
