### ISSUE TITLE
Duplicate Accessories in Homebridge

### ISSUE THREAD

**Issue by left-aligned** [dgreif/homebridge-hatch-baby-rest#79]
Thank you for this awesome plugin. I've set it up in my Homebridge, but I seem to get duplicate accessories no matter my configuration. When using the setup I name my Rest+ "Night Light". In the accessories section I see controls for "Night Light" and for "My Rest+". Is this supposed to happen?

These accessories show up in my Homekit. Same thing happens whether I use a child bridge or not.

![Screen Shot 2022-07-13 at 12 22 52 PM](https://user-images.githubusercontent.com/85647731/178814864-f201501b-d0d7-4082-a65c-595a77c7569a.png)

**Comment by dgreif** [comment]
No, it shouldn't duplicate them.  Did it only do this after you renamed the light?

**Comment by left-aligned** [comment]
I see the issue now. When following the setup I was entering my email/password and also filling out the "Light Name" and "MAC Address" section. I have a Rest+, didn't realize I didn't need to fill out that section either.
