### ISSUE TITLE
Unsupported Product Found: riotPlus

### ISSUE THREAD

**Issue by danshaw** [dgreif/homebridge-hatch-baby-rest#83]
I just picked up a Hatch Rest+ 2nd Gen. After setting it up and installing the plugin, I get the following error:

`[9/2/2022, 9:56:47 AM] [HatchBabyRest] Unsupported Product Found: riotPlus
[9/2/2022, 9:56:47 AM] [HatchBabyRest] Configuring 0 Rest, 0 Rest+, 0 Rest Mini, 0 Rest 2nd Gen, and 0 Restore`

Any idea why it thinks it's unsupported?

Edit: I did a little digging, and it looks like that codeword "riot" is being used in certain versions.

https://usermanual.wiki/Hatch-Baby/HBREST2/info

**Comment by dgreif** [comment]
Looks like this is a brand new device! I don't even see it on their website yet. I'm going to make an assumption that the data is a similar shape to the `riot`, but that may be totally false. Give v3.4.0-beta.0 and let me know if it works 🤞

**Comment by danshaw** [comment]
Thanks @dgreif, that did the trick. Iv'e read through a lot of the discussions regarding what is possible and what is not and it sounds like there are some limitations you are hitting with the Rest+ in regards to color and sound, but wanted to thank you for putting the time in to make this. If you do ever find the time or the access to add the ability to change colors/volume, that would benefit me greatly. We have a few different colors set which correlate to a different scenarios and we rarely just turn the Hatch on and off. Either way, this is 100x easier to turn off now via Homekit vs having to go into the app and wait for it to connect. Wish they made it easier for you to integrate!

**Comment by dgreif** [comment]
@danshaw thanks for the input! Glad to hear the new light is working. I've released 3.4.0 to officially support it
