### ISSUE TITLE
Failed install on synology DSM 7

### ISSUE THREAD

**Issue by 6MH89F3j** [dgreif/homebridge-hatch-baby-rest#84]
Hello,

I am unable to get this plugin to install on my Synology homebridge setup. I have the ring plugin running well (thank you btw!).

Seems like the same exact problem as #70.

I read your response to follow instructions at https://www.npmjs.com/package/@abandonware/noble#installation or to google "node gyp Synology", and after reading through those, I am not sure what to do next.

I am running on Synology ds420+ NAS, of which has cpu 'Intel Celeron J4025', and am running DSM 7.1

I installed Homebridge natively on DSM. https://github.com/oznu/homebridge-syno-spk#how-to-install

I did find this, of which sounds related to the issue I'm having. https://github.com/oznu/homebridge-syno-spk/wiki/DSM-7:-Enable-Compiling-Of-Native-Modules

Before I start running commands on my NAS and installing things, I figured I would ask here, to see if you think it might fix the problem I'm having? Or, if I should be looking in a different direction.

**Comment by dgreif** [comment]
I don't have any useful tips based on your setup. The instructions in the abandonware noble repo are the best that I can offer, and it sounds like you are following those already.

**Comment by 6MH89F3j** [comment]
FYI, I saw that you split out the plugins to remove the need for bluetooth support. The recent v4.0.0 of homebridge-hatch-baby-rest is now working for me on DSM7! Thank you so much!!
