### ISSUE TITLE
Rest Gen 2 doesn't show color settings

### ISSUE THREAD

**Issue by lukehoersten** [dgreif/homebridge-hatch-baby-rest#89]
Unable to change color - accessory only makes light+sound on/off switch and dimmer available.

- Version: Rest Gen 2
- Homebridge Version: 1.5.0
- homebridge-hatch-baby-rest v3.4.0
- Firmware Revision | 7.1.360

**Comment by dgreif** [comment]
Some of the newer devices have a much more complicated API, mainly based on routines and presets. They don't have a simple way of setting color/sound, which is why the plugin only exposes the on/off switch.
