### ISSUE TITLE
Ongoing issue

### ISSUE THREAD

**Issue by wildd86** [dgreif/homebridge-hatch-baby-rest#9]
I believe I've done everything correctly, but I keep getting the following error on repeat when I launch homebridge: "Failed to reach Hatch Baby server at https://data.hatchbaby.com/public/v1/login.  Trying again in 5 seconds..."

I can't tell if this is an error on their side or mine.

**Comment by dgreif** [comment]
@wildd86 sorry I didn't get back to you sooner.  That message looks like you were having general network issues, which prevented the plugin from reaching the hatch baby servers.  Can you give it another try?
