### ISSUE TITLE
Added to homekit but buttons do nothing (rest+ 2nd gen)

### ISSUE THREAD

**Issue by eoddc5** [dgreif/homebridge-hatch-baby-rest#93]
Hi. Just got a rest+ 2nd gen
does this matter? Is this supported? Or only first gen rest?

I added the device. It shows three buttons (fan, light, switch) but none do any action. They show they’re adjusting in home, but they don’t do anything for the rest device itself

Just wanted to check with you if you have any thoughts

![1ABE9D56-1D4D-43F0-B6CE-9F9AEBAB3733](https://user-images.githubusercontent.com/10222895/197364970-26238d1c-9675-49f5-bb8b-3cd208ecc30a.jpeg)

**Comment by eoddc5** [comment]
So when I originally configured this I added my device name and mac, thinking I needed it

since I didn’t, I removed that info, saved, and reboot

now the switch button works to turn on the f1 noise and light combo but the other two icons disappeared

**Comment by dgreif** [comment]
With the Rest+ 2nd gen, you only get an on/off switch because the settings for the light do not play well with what is available in HomeKit. Sounds like it's working as expected now
