### ISSUE TITLE
Issue installing on Synology DSM7 package, continues to fail

### ISSUE THREAD

**Issue by chrisgruggen** [dgreif/homebridge-hatch-baby-rest#95]
Tried installing via homebridge ui and terminal and both times the install failed. 

I was able to get it to work if I installed homebridge in docker, but then I was having other issues with Homebridge connecting to my HomeKit, so I reverted back to the Synology package. 

> homebridge@Synology:/volume1/homebridge $ npm i -g homebridge-hatch-baby-rest
> npm ERR! code 1
> npm ERR! path /volume1/@appstore/homebridge/app/lib/node_modules/homebridge-hatch-baby-rest/node_modules/@abandonware/noble
> npm ERR! command failed
> npm ERR! command sh -c node-gyp rebuild
> npm ERR! gyp ERR! build error 
> npm ERR! gyp ERR! stack Error: not found: make
> npm ERR! gyp ERR! stack     at getNotFoundError (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:10:17)
> npm ERR! gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:57:18
> npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
> npm ERR! gyp ERR! stack     at step (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:54:21)
> npm ERR! gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:71:22
> npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
> npm ERR! gyp ERR! stack     at subStep (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:69:33)
> npm ERR! gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:80:22
> npm ERR! gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/index.js:42:5
> npm ERR! gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
> npm ERR! gyp ERR! System Linux 4.4.180+
> npm ERR! gyp ERR! command "/volume1/@appstore/homebridge/app/bin/node" "/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> npm ERR! gyp ERR! cwd /volume1/@appstore/homebridge/app/lib/node_modules/homebridge-hatch-baby-rest/node_modules/@abandonware/noble
> npm ERR! gyp ERR! node -v v16.16.0
> npm ERR! gyp ERR! node-gyp -v v9.0.0
> npm ERR! gyp ERR! not ok
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /var/packages/homebridge/home/.npm/_logs/2022-11-05T13_25_37_936Z-debug-0.log
> homebridge@Synology:/volume1/homebridge $

```

**Comment by dgreif** [comment]
I've finally decided to move forward with splitting the bluetooth lights into their own `homebridge-hatch-rest-bluetooth` plugin. You should be to install `homebridge-hatch-baby-rest` version `4.0.0` without jumping through any bluetooth hoops now, as long as wifi sound machines are all you need access to. Please let me know if that works for you!

**Comment by 6MH89F3j** [comment]
FYI, I was having this same exact issue. I installed 4.0.0 of homebridge-hatch-baby-rest and it's working perfectly for me on DSM7! Thank you so much!!
